apiVersion: v1
kind: Service
metadata:
  name: {{ include "jevai-mcp.fullname" . }}
  labels:
        {{- include "jevai-mcp.labels" . | nindent 4 }}
   {{- with .Values.service.annotations }}
  annotations:
        {{- toYaml . | nindent 4 }}
   {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: mcp
      port: {{ .Values.service.mcpPort }}
      targetPort: mcp
  selector:
        {{- include "jevai-mcp.selectorLabels" . | nindent 4 }}
