apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: jevai-mcp-data
   labels:
      app.kubernetes.io/name: jevai-mcp
spec:
   accessModes:
       - ReadWriteOnce
   resources:
      requests:
         storage: 2Gi
   # storageClassName: standard
